[theme]
primaryColor = "#f5faf5"                
backgroundColor = "#91AC8F" 
secondaryBackgroundColor = "#537D5D"
textColor = "#fcfcfc"                   
font = "Poppins"

[server]
headless = true

[browser]
serverAddress = "0.0.0.0"

# Set timezone
[theme]
base = "light"

# Environment variables
[env]
TZ = "Asia/Jakarta"
